# -*- coding: utf-8 -*-
"""python_ch3_15

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zikV-p5XvdlsUbMPFiKEwZYjiWoQkigp

CH03_15. 피벗테이블
"""

import pandas as pd
import numpy as np

#문제: 다음 데이터프레임은 A 서비스의 월별 탈퇴 회원수를 가입 월별로 분류해 놓은 것이다. 이 데이터프레임을 이용하여 피벗테이블을 만드시오.
df=pd.DataFrame({'가입월': [1, 1, 1, 2, 2, 3], '탈퇴월': [1, 2, 3, 2, 3, 3], '탈퇴회원수': [101, 52, 30, 120, 60, 130]})

df

pivot=pd.pivot_table(df, values='탈퇴회원수', index=['가입월'], columns=['탈퇴월'])

type(pivot)

pivot

pivot=pd.pivot_table(df, values='탈퇴회원수', index=['가입월'], columns=['탈퇴월'], fill_value=0)

pivot

#문제: 다음 데이터프레임은 어느 과일 매장의 판매 내역이다. 각 상품 항목별, 크기별로 판매 개수와 판매 금액의 합을 구하시오.
import random

random.randint(1, 3)

a=[]
b=[]

for i in range(100):
  a.append(random.randint(1, 3))
  b.append(random.randint(1, 3)) #1에서 100까지 수 중에서 a,b 리스트에 1에서 3 사이의 수를 랜덤으로 추가

df=pd.DataFrame({'품목': a, '크기': b})

df

df['금액']=df['품목']*df['크기']*500
df['수수료']=df['금액']*0.1

df

fruit_name={1: '토마토', 2: '바나나', 3: '사과'}
fruit_size={1: '소', 2: '중', 3: '대'}

df['품목']=df['품목'].map(fruit_name)
df['크기']=df['크기'].map(fruit_size)

df

pd.pivot_table(df, values='금액', index=['품목'], columns=['크기'], aggfunc=('count', 'sum'))

#문제: 다음 데이터프레임은 어느 과일 매장의 판매내역이다. 각 상품 항목별, 크기별로 판매 개수와 판매 금액/수수료의 합을 구하시오.
df

df.pivot_table(df, index=['품목'], columns=['크기'], aggfunc={'금액': ['count', 'sum'], '수수료': 'sum'})

