# -*- coding: utf-8 -*-
"""python_ch3_14

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ARzhaNf4XDn7MFZVC2PqmPwrhxSovGCe
"""

pip install pandas

"""#CH03_14. 그룹화"""

import pandas as pd

df1 =pd.DataFrame({'ID': [1, 2, 3, 4, 5], '가입일': ['2021-01-02', '2021-01-04', '2021-01-10', '2021-02-10', '2021-02-24'], '성별': ['F', 'M', 'F', 'M', 'M']})
df2 =pd.DataFrame({'구매순서': [1, 2, 3, 4, 5], 'ID': [1, 1, 2, 4, 1], '구매월': [1, 1, 2, 2, 3], '금액': [1000, 1500, 2000, 3000, 4000]})

#문제: df1은 회원의 정보를 저장한 데이터프레임이며, df2는 각 회원의 구매 내역을 저장한 데이터프레임이다. 각 회원의 정보와 구매 내역을 취합하여 하나의 데이터프레임으로 만드시오.
pd.merge(df1, df2, how='left', on='ID')

#문제: df1은 회원의 정보를 저장한 데이터프레임이며, df2는 각 회원의 구매 내역을 저장한 데이터프레임이다. 각 회원의 누적 금액을 회원 ID별로 구하시오.
df2

df2.groupby(by=['ID'])['금액'].sum() #groupby = 통계, 합산

type(df2.groupby(by=['ID'])['금액'].sum())

s2=df2.groupby(by=['ID'])['금액'].sum()

pd.merge(df1, s2, how='left', on='ID')

#문제: df1은 회원의 정보를 저장한 데이터프레임이며, df2는 각 회원의 구매 내역을 저장한 데이터프레임이다. 각 회원의 월별 누적 금액을 회원 ID별로 구하시오.
df2.groupby(by=['ID', '구매월'])['금액'].sum() #df2를 ID와 구매일만 나타내서 나타냄, 금액 부분은 모두 더한 값

type(df2.groupby(by=['ID', '구매월'])['금액'].sum())

s2=df2.groupby(by=['ID', '구매월'])['금액'].sum()

s2.index

pd.merge(df1, s2, how='left', on='ID')

s2

df3=pd.DataFrame(s2)

df1

df3

df3.index

pd.merge(df1, df3, how='left', on='ID')

#그룹을 index로 사용하고 싶지 않은 경우에는 as_index=False로 설정
df2.groupby(by=['ID', '구매월'], as_index=False)['금액'].sum()

type(df2.groupby(by=['ID', '구매월'], as_index=False)['금액'].sum())

df3=df2.groupby(by=['ID', '구매월'], as_index=False)['금액'].sum()

pd.merge(df1, df3, how='left', on='ID')

#문제: df는 각 회원의 구매 내역을 저장한 데이터프레임이다. 각 회원의 누적 금액과 누적 구매 횟수를 회원 ID별로 구하시오.
df=pd.DataFrame({'구매순서': [1, 2, 3, 4, 5], 'ID': [1, 1, 2, 4, 1], '구매월': [1, 1, 2, 2, 3], '금액': [1000, 1500, 2000, 3000, 4000], '수수료': [100, 150, 200, 300, 400]})
df

df.groupby(by=['ID'])['금액'].agg([sum, len])

df.groupby(by=['ID'], as_index=False)['금액'].agg([sum, len]) #agg랑 as_index 호환 불가, 아무 일도 일어나지 않음

df2=df.groupby(by=['ID'])['금액'].agg([sum, len])

df2.reset_index(inplace=True)

df2

#문제: df는 각 회원의 구매 내역을 저장한 데이터프레임이다. 각 회원의 최대 사용 금액/최소 사용 금액과 최저 수수료의 값을 구하시오.
df

df.groupby(by=['ID']).agg({'금액': [max, min], '수수료':min})

df2=df.groupby(by=['ID']).agg({'금액': [max, min], '수수료':min})

df2.reset_index()

df2.columns

df2.columns=['_'.join(col) for col in df2.columns.values] #df2의 칼럼들을 '_'로 조인

df2

df2.reset_index()

