# -*- coding: utf-8 -*-
"""CH04_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YC677YLKUPwfAvTODl1upbxrAvgyuCo0
"""

import matplotlib.pyplot as plt


x = [1, 2, 3]
y = [1, 2, 3]

plt.figure()
plt.plot(x, y)

plt.plot(y)


plt.plot(x, y, linewidth=10)
plt.plot(x, y, color='red')
plt.plot(x, y, marker='o')
plt.plot(x, y, marker='o', markersize=10)
plt.plot(x, y, linestyle=':')
plt.plot(x, y, ':')
plt.plot(x, y, 'ro')


plt.plot(x, y)
plt.title('title')
plt.title('title', fontsize=25)

plt.plot(x, y)
plt.xlabel('x')
plt.ylabel('y')

plt.plot(x, y)
plt.xlabel('x', fontsize=20)
plt.ylabel('y', fontsize=20)

plt.plot(x, y)
plt.grid(True)
plt.plot(x, y)
plt.grid(True, axis='x')

plt.plot(x, y)
plt.grid(True, axis='y')

plt.plot(x, y)
plt.xlim([1, 2])
plt.ylim([1, 2])


plt.plot(x, y)
plt.axis([1, 2, 4, 5])
plt.plot(x, y)
plt.xticks(fontsize=25)
plt.yticks(fontsize=30)
plt.plot(x, y)

plt.plot(x)
plt.title('차트')
plt.show()

